### ISSUE TITLE
Virus? - No it isn't. 

### ISSUE THREAD

**Issue by JUSTaMod** [NotPocketMine/Windows-PocketMine-MP#1]
Comment removed due to false accusations  

Read this link below for details
https://forums.pmmp.io/threads/pocketmine-mp-1-6-2-installer-windows.2022/page-2#post-28365

**Comment by TheDeibo** [comment]
Any more virus accusations, I am willing to download (and record) free antiviruses and malware detectors to show as proof. 

AVG: No Viruses shown on my PocketMine Installer, or even after It's executed.
MalwareBytes: No Viruses shown on my PocketMine Installer, or even after It's executed.
Norton: No Viruses shown on my PocketMine Installer, or even after It's executed.
Sophos: No Viruses shown on my PocketMine Installer, or even after It's executed.
